// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: human.proto

package resources;

public final class HumanProto {
  private HumanProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HumanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:resources.Human)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 10001;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 10001;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int64 age = 2;</code>
     */
    long getAge();

    /**
     * <code>string place_of_birth = 3;</code>
     */
    java.lang.String getPlaceOfBirth();
    /**
     * <code>string place_of_birth = 3;</code>
     */
    com.google.protobuf.ByteString
        getPlaceOfBirthBytes();

    /**
     * <code>repeated string nick_names = 4;</code>
     */
    java.util.List<java.lang.String>
        getNickNamesList();
    /**
     * <code>repeated string nick_names = 4;</code>
     */
    int getNickNamesCount();
    /**
     * <code>repeated string nick_names = 4;</code>
     */
    java.lang.String getNickNames(int index);
    /**
     * <code>repeated string nick_names = 4;</code>
     */
    com.google.protobuf.ByteString
        getNickNamesBytes(int index);

    /**
     * <code>.resources.Human.HumanType human_type = 5;</code>
     */
    int getHumanTypeValue();
    /**
     * <code>.resources.Human.HumanType human_type = 5;</code>
     */
    resources.HumanProto.Human.HumanType getHumanType();

    /**
     * <code>.resources.Human.Address address = 6;</code>
     */
    boolean hasAddress();
    /**
     * <code>.resources.Human.Address address = 6;</code>
     */
    resources.HumanProto.Human.Address getAddress();
    /**
     * <code>.resources.Human.Address address = 6;</code>
     */
    resources.HumanProto.Human.AddressOrBuilder getAddressOrBuilder();
  }
  /**
   * Protobuf type {@code resources.Human}
   */
  public  static final class Human extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:resources.Human)
      HumanOrBuilder {
    // Use Human.newBuilder() to construct.
    private Human(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Human() {
      id_ = "";
      name_ = "";
      age_ = 0L;
      placeOfBirth_ = "";
      nickNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      humanType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Human(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              placeOfBirth_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                nickNames_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              nickNames_.add(s);
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              humanType_ = rawValue;
              break;
            }
            case 50: {
              resources.HumanProto.Human.Address.Builder subBuilder = null;
              if (address_ != null) {
                subBuilder = address_.toBuilder();
              }
              address_ = input.readMessage(resources.HumanProto.Human.Address.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(address_);
                address_ = subBuilder.buildPartial();
              }

              break;
            }
            case 80010: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          nickNames_ = nickNames_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return resources.HumanProto.internal_static_resources_Human_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return resources.HumanProto.internal_static_resources_Human_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              resources.HumanProto.Human.class, resources.HumanProto.Human.Builder.class);
    }

    /**
     * Protobuf enum {@code resources.Human.HumanType}
     */
    public enum HumanType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUPER_HUMAN = 0;</code>
       */
      SUPER_HUMAN(0),
      /**
       * <code>NORMAL_HUMAN = 1;</code>
       */
      NORMAL_HUMAN(1),
      /**
       * <code>SUB_HUMAN = 2;</code>
       */
      SUB_HUMAN(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>SUPER_HUMAN = 0;</code>
       */
      public static final int SUPER_HUMAN_VALUE = 0;
      /**
       * <code>NORMAL_HUMAN = 1;</code>
       */
      public static final int NORMAL_HUMAN_VALUE = 1;
      /**
       * <code>SUB_HUMAN = 2;</code>
       */
      public static final int SUB_HUMAN_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static HumanType valueOf(int value) {
        return forNumber(value);
      }

      public static HumanType forNumber(int value) {
        switch (value) {
          case 0: return SUPER_HUMAN;
          case 1: return NORMAL_HUMAN;
          case 2: return SUB_HUMAN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<HumanType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          HumanType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<HumanType>() {
              public HumanType findValueByNumber(int number) {
                return HumanType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return resources.HumanProto.Human.getDescriptor().getEnumTypes().get(0);
      }

      private static final HumanType[] VALUES = values();

      public static HumanType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private HumanType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:resources.Human.HumanType)
    }

    public interface AddressOrBuilder extends
        // @@protoc_insertion_point(interface_extends:resources.Human.Address)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string address_line_1 = 1;</code>
       */
      java.lang.String getAddressLine1();
      /**
       * <code>string address_line_1 = 1;</code>
       */
      com.google.protobuf.ByteString
          getAddressLine1Bytes();

      /**
       * <code>string address_line_2 = 2;</code>
       */
      java.lang.String getAddressLine2();
      /**
       * <code>string address_line_2 = 2;</code>
       */
      com.google.protobuf.ByteString
          getAddressLine2Bytes();

      /**
       * <code>string address_line_3 = 3;</code>
       */
      java.lang.String getAddressLine3();
      /**
       * <code>string address_line_3 = 3;</code>
       */
      com.google.protobuf.ByteString
          getAddressLine3Bytes();
    }
    /**
     * Protobuf type {@code resources.Human.Address}
     */
    public  static final class Address extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:resources.Human.Address)
        AddressOrBuilder {
      // Use Address.newBuilder() to construct.
      private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Address() {
        addressLine1_ = "";
        addressLine2_ = "";
        addressLine3_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private Address(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                addressLine1_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                addressLine2_ = s;
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();

                addressLine3_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return resources.HumanProto.internal_static_resources_Human_Address_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return resources.HumanProto.internal_static_resources_Human_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                resources.HumanProto.Human.Address.class, resources.HumanProto.Human.Address.Builder.class);
      }

      public static final int ADDRESS_LINE_1_FIELD_NUMBER = 1;
      private volatile java.lang.Object addressLine1_;
      /**
       * <code>string address_line_1 = 1;</code>
       */
      public java.lang.String getAddressLine1() {
        java.lang.Object ref = addressLine1_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          addressLine1_ = s;
          return s;
        }
      }
      /**
       * <code>string address_line_1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAddressLine1Bytes() {
        java.lang.Object ref = addressLine1_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          addressLine1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ADDRESS_LINE_2_FIELD_NUMBER = 2;
      private volatile java.lang.Object addressLine2_;
      /**
       * <code>string address_line_2 = 2;</code>
       */
      public java.lang.String getAddressLine2() {
        java.lang.Object ref = addressLine2_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          addressLine2_ = s;
          return s;
        }
      }
      /**
       * <code>string address_line_2 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAddressLine2Bytes() {
        java.lang.Object ref = addressLine2_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          addressLine2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ADDRESS_LINE_3_FIELD_NUMBER = 3;
      private volatile java.lang.Object addressLine3_;
      /**
       * <code>string address_line_3 = 3;</code>
       */
      public java.lang.String getAddressLine3() {
        java.lang.Object ref = addressLine3_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          addressLine3_ = s;
          return s;
        }
      }
      /**
       * <code>string address_line_3 = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAddressLine3Bytes() {
        java.lang.Object ref = addressLine3_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          addressLine3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getAddressLine1Bytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, addressLine1_);
        }
        if (!getAddressLine2Bytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, addressLine2_);
        }
        if (!getAddressLine3Bytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, addressLine3_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getAddressLine1Bytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, addressLine1_);
        }
        if (!getAddressLine2Bytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, addressLine2_);
        }
        if (!getAddressLine3Bytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, addressLine3_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof resources.HumanProto.Human.Address)) {
          return super.equals(obj);
        }
        resources.HumanProto.Human.Address other = (resources.HumanProto.Human.Address) obj;

        boolean result = true;
        result = result && getAddressLine1()
            .equals(other.getAddressLine1());
        result = result && getAddressLine2()
            .equals(other.getAddressLine2());
        result = result && getAddressLine3()
            .equals(other.getAddressLine3());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ADDRESS_LINE_1_FIELD_NUMBER;
        hash = (53 * hash) + getAddressLine1().hashCode();
        hash = (37 * hash) + ADDRESS_LINE_2_FIELD_NUMBER;
        hash = (53 * hash) + getAddressLine2().hashCode();
        hash = (37 * hash) + ADDRESS_LINE_3_FIELD_NUMBER;
        hash = (53 * hash) + getAddressLine3().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static resources.HumanProto.Human.Address parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static resources.HumanProto.Human.Address parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static resources.HumanProto.Human.Address parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static resources.HumanProto.Human.Address parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static resources.HumanProto.Human.Address parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static resources.HumanProto.Human.Address parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static resources.HumanProto.Human.Address parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static resources.HumanProto.Human.Address parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static resources.HumanProto.Human.Address parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static resources.HumanProto.Human.Address parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(resources.HumanProto.Human.Address prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code resources.Human.Address}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:resources.Human.Address)
          resources.HumanProto.Human.AddressOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return resources.HumanProto.internal_static_resources_Human_Address_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return resources.HumanProto.internal_static_resources_Human_Address_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  resources.HumanProto.Human.Address.class, resources.HumanProto.Human.Address.Builder.class);
        }

        // Construct using resources.HumanProto.Human.Address.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          addressLine1_ = "";

          addressLine2_ = "";

          addressLine3_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return resources.HumanProto.internal_static_resources_Human_Address_descriptor;
        }

        public resources.HumanProto.Human.Address getDefaultInstanceForType() {
          return resources.HumanProto.Human.Address.getDefaultInstance();
        }

        public resources.HumanProto.Human.Address build() {
          resources.HumanProto.Human.Address result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public resources.HumanProto.Human.Address buildPartial() {
          resources.HumanProto.Human.Address result = new resources.HumanProto.Human.Address(this);
          result.addressLine1_ = addressLine1_;
          result.addressLine2_ = addressLine2_;
          result.addressLine3_ = addressLine3_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof resources.HumanProto.Human.Address) {
            return mergeFrom((resources.HumanProto.Human.Address)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(resources.HumanProto.Human.Address other) {
          if (other == resources.HumanProto.Human.Address.getDefaultInstance()) return this;
          if (!other.getAddressLine1().isEmpty()) {
            addressLine1_ = other.addressLine1_;
            onChanged();
          }
          if (!other.getAddressLine2().isEmpty()) {
            addressLine2_ = other.addressLine2_;
            onChanged();
          }
          if (!other.getAddressLine3().isEmpty()) {
            addressLine3_ = other.addressLine3_;
            onChanged();
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          resources.HumanProto.Human.Address parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (resources.HumanProto.Human.Address) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object addressLine1_ = "";
        /**
         * <code>string address_line_1 = 1;</code>
         */
        public java.lang.String getAddressLine1() {
          java.lang.Object ref = addressLine1_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            addressLine1_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string address_line_1 = 1;</code>
         */
        public com.google.protobuf.ByteString
            getAddressLine1Bytes() {
          java.lang.Object ref = addressLine1_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            addressLine1_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string address_line_1 = 1;</code>
         */
        public Builder setAddressLine1(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          addressLine1_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string address_line_1 = 1;</code>
         */
        public Builder clearAddressLine1() {
          
          addressLine1_ = getDefaultInstance().getAddressLine1();
          onChanged();
          return this;
        }
        /**
         * <code>string address_line_1 = 1;</code>
         */
        public Builder setAddressLine1Bytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          addressLine1_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object addressLine2_ = "";
        /**
         * <code>string address_line_2 = 2;</code>
         */
        public java.lang.String getAddressLine2() {
          java.lang.Object ref = addressLine2_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            addressLine2_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string address_line_2 = 2;</code>
         */
        public com.google.protobuf.ByteString
            getAddressLine2Bytes() {
          java.lang.Object ref = addressLine2_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            addressLine2_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string address_line_2 = 2;</code>
         */
        public Builder setAddressLine2(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          addressLine2_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string address_line_2 = 2;</code>
         */
        public Builder clearAddressLine2() {
          
          addressLine2_ = getDefaultInstance().getAddressLine2();
          onChanged();
          return this;
        }
        /**
         * <code>string address_line_2 = 2;</code>
         */
        public Builder setAddressLine2Bytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          addressLine2_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object addressLine3_ = "";
        /**
         * <code>string address_line_3 = 3;</code>
         */
        public java.lang.String getAddressLine3() {
          java.lang.Object ref = addressLine3_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            addressLine3_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string address_line_3 = 3;</code>
         */
        public com.google.protobuf.ByteString
            getAddressLine3Bytes() {
          java.lang.Object ref = addressLine3_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            addressLine3_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string address_line_3 = 3;</code>
         */
        public Builder setAddressLine3(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          addressLine3_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string address_line_3 = 3;</code>
         */
        public Builder clearAddressLine3() {
          
          addressLine3_ = getDefaultInstance().getAddressLine3();
          onChanged();
          return this;
        }
        /**
         * <code>string address_line_3 = 3;</code>
         */
        public Builder setAddressLine3Bytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          addressLine3_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:resources.Human.Address)
      }

      // @@protoc_insertion_point(class_scope:resources.Human.Address)
      private static final resources.HumanProto.Human.Address DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new resources.HumanProto.Human.Address();
      }

      public static resources.HumanProto.Human.Address getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Address>
          PARSER = new com.google.protobuf.AbstractParser<Address>() {
        public Address parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Address(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Address> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Address> getParserForType() {
        return PARSER;
      }

      public resources.HumanProto.Human.Address getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 10001;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 10001;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 10001;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private long age_;
    /**
     * <code>int64 age = 2;</code>
     */
    public long getAge() {
      return age_;
    }

    public static final int PLACE_OF_BIRTH_FIELD_NUMBER = 3;
    private volatile java.lang.Object placeOfBirth_;
    /**
     * <code>string place_of_birth = 3;</code>
     */
    public java.lang.String getPlaceOfBirth() {
      java.lang.Object ref = placeOfBirth_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        placeOfBirth_ = s;
        return s;
      }
    }
    /**
     * <code>string place_of_birth = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPlaceOfBirthBytes() {
      java.lang.Object ref = placeOfBirth_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        placeOfBirth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICK_NAMES_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList nickNames_;
    /**
     * <code>repeated string nick_names = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getNickNamesList() {
      return nickNames_;
    }
    /**
     * <code>repeated string nick_names = 4;</code>
     */
    public int getNickNamesCount() {
      return nickNames_.size();
    }
    /**
     * <code>repeated string nick_names = 4;</code>
     */
    public java.lang.String getNickNames(int index) {
      return nickNames_.get(index);
    }
    /**
     * <code>repeated string nick_names = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNickNamesBytes(int index) {
      return nickNames_.getByteString(index);
    }

    public static final int HUMAN_TYPE_FIELD_NUMBER = 5;
    private int humanType_;
    /**
     * <code>.resources.Human.HumanType human_type = 5;</code>
     */
    public int getHumanTypeValue() {
      return humanType_;
    }
    /**
     * <code>.resources.Human.HumanType human_type = 5;</code>
     */
    public resources.HumanProto.Human.HumanType getHumanType() {
      resources.HumanProto.Human.HumanType result = resources.HumanProto.Human.HumanType.valueOf(humanType_);
      return result == null ? resources.HumanProto.Human.HumanType.UNRECOGNIZED : result;
    }

    public static final int ADDRESS_FIELD_NUMBER = 6;
    private resources.HumanProto.Human.Address address_;
    /**
     * <code>.resources.Human.Address address = 6;</code>
     */
    public boolean hasAddress() {
      return address_ != null;
    }
    /**
     * <code>.resources.Human.Address address = 6;</code>
     */
    public resources.HumanProto.Human.Address getAddress() {
      return address_ == null ? resources.HumanProto.Human.Address.getDefaultInstance() : address_;
    }
    /**
     * <code>.resources.Human.Address address = 6;</code>
     */
    public resources.HumanProto.Human.AddressOrBuilder getAddressOrBuilder() {
      return getAddress();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0L) {
        output.writeInt64(2, age_);
      }
      if (!getPlaceOfBirthBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, placeOfBirth_);
      }
      for (int i = 0; i < nickNames_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, nickNames_.getRaw(i));
      }
      if (humanType_ != resources.HumanProto.Human.HumanType.SUPER_HUMAN.getNumber()) {
        output.writeEnum(5, humanType_);
      }
      if (address_ != null) {
        output.writeMessage(6, getAddress());
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10001, id_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, age_);
      }
      if (!getPlaceOfBirthBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, placeOfBirth_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < nickNames_.size(); i++) {
          dataSize += computeStringSizeNoTag(nickNames_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getNickNamesList().size();
      }
      if (humanType_ != resources.HumanProto.Human.HumanType.SUPER_HUMAN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, humanType_);
      }
      if (address_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getAddress());
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10001, id_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof resources.HumanProto.Human)) {
        return super.equals(obj);
      }
      resources.HumanProto.Human other = (resources.HumanProto.Human) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && (getAge()
          == other.getAge());
      result = result && getPlaceOfBirth()
          .equals(other.getPlaceOfBirth());
      result = result && getNickNamesList()
          .equals(other.getNickNamesList());
      result = result && humanType_ == other.humanType_;
      result = result && (hasAddress() == other.hasAddress());
      if (hasAddress()) {
        result = result && getAddress()
            .equals(other.getAddress());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAge());
      hash = (37 * hash) + PLACE_OF_BIRTH_FIELD_NUMBER;
      hash = (53 * hash) + getPlaceOfBirth().hashCode();
      if (getNickNamesCount() > 0) {
        hash = (37 * hash) + NICK_NAMES_FIELD_NUMBER;
        hash = (53 * hash) + getNickNamesList().hashCode();
      }
      hash = (37 * hash) + HUMAN_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + humanType_;
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static resources.HumanProto.Human parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static resources.HumanProto.Human parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static resources.HumanProto.Human parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static resources.HumanProto.Human parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static resources.HumanProto.Human parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static resources.HumanProto.Human parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static resources.HumanProto.Human parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static resources.HumanProto.Human parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static resources.HumanProto.Human parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static resources.HumanProto.Human parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(resources.HumanProto.Human prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code resources.Human}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:resources.Human)
        resources.HumanProto.HumanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return resources.HumanProto.internal_static_resources_Human_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return resources.HumanProto.internal_static_resources_Human_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                resources.HumanProto.Human.class, resources.HumanProto.Human.Builder.class);
      }

      // Construct using resources.HumanProto.Human.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        name_ = "";

        age_ = 0L;

        placeOfBirth_ = "";

        nickNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        humanType_ = 0;

        if (addressBuilder_ == null) {
          address_ = null;
        } else {
          address_ = null;
          addressBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return resources.HumanProto.internal_static_resources_Human_descriptor;
      }

      public resources.HumanProto.Human getDefaultInstanceForType() {
        return resources.HumanProto.Human.getDefaultInstance();
      }

      public resources.HumanProto.Human build() {
        resources.HumanProto.Human result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public resources.HumanProto.Human buildPartial() {
        resources.HumanProto.Human result = new resources.HumanProto.Human(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        result.age_ = age_;
        result.placeOfBirth_ = placeOfBirth_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          nickNames_ = nickNames_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.nickNames_ = nickNames_;
        result.humanType_ = humanType_;
        if (addressBuilder_ == null) {
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof resources.HumanProto.Human) {
          return mergeFrom((resources.HumanProto.Human)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(resources.HumanProto.Human other) {
        if (other == resources.HumanProto.Human.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0L) {
          setAge(other.getAge());
        }
        if (!other.getPlaceOfBirth().isEmpty()) {
          placeOfBirth_ = other.placeOfBirth_;
          onChanged();
        }
        if (!other.nickNames_.isEmpty()) {
          if (nickNames_.isEmpty()) {
            nickNames_ = other.nickNames_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureNickNamesIsMutable();
            nickNames_.addAll(other.nickNames_);
          }
          onChanged();
        }
        if (other.humanType_ != 0) {
          setHumanTypeValue(other.getHumanTypeValue());
        }
        if (other.hasAddress()) {
          mergeAddress(other.getAddress());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        resources.HumanProto.Human parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (resources.HumanProto.Human) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 10001;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 10001;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 10001;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 10001;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 10001;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private long age_ ;
      /**
       * <code>int64 age = 2;</code>
       */
      public long getAge() {
        return age_;
      }
      /**
       * <code>int64 age = 2;</code>
       */
      public Builder setAge(long value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 age = 2;</code>
       */
      public Builder clearAge() {
        
        age_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object placeOfBirth_ = "";
      /**
       * <code>string place_of_birth = 3;</code>
       */
      public java.lang.String getPlaceOfBirth() {
        java.lang.Object ref = placeOfBirth_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          placeOfBirth_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string place_of_birth = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPlaceOfBirthBytes() {
        java.lang.Object ref = placeOfBirth_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          placeOfBirth_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string place_of_birth = 3;</code>
       */
      public Builder setPlaceOfBirth(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        placeOfBirth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string place_of_birth = 3;</code>
       */
      public Builder clearPlaceOfBirth() {
        
        placeOfBirth_ = getDefaultInstance().getPlaceOfBirth();
        onChanged();
        return this;
      }
      /**
       * <code>string place_of_birth = 3;</code>
       */
      public Builder setPlaceOfBirthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        placeOfBirth_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList nickNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureNickNamesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          nickNames_ = new com.google.protobuf.LazyStringArrayList(nickNames_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string nick_names = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getNickNamesList() {
        return nickNames_.getUnmodifiableView();
      }
      /**
       * <code>repeated string nick_names = 4;</code>
       */
      public int getNickNamesCount() {
        return nickNames_.size();
      }
      /**
       * <code>repeated string nick_names = 4;</code>
       */
      public java.lang.String getNickNames(int index) {
        return nickNames_.get(index);
      }
      /**
       * <code>repeated string nick_names = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNickNamesBytes(int index) {
        return nickNames_.getByteString(index);
      }
      /**
       * <code>repeated string nick_names = 4;</code>
       */
      public Builder setNickNames(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNickNamesIsMutable();
        nickNames_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string nick_names = 4;</code>
       */
      public Builder addNickNames(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNickNamesIsMutable();
        nickNames_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string nick_names = 4;</code>
       */
      public Builder addAllNickNames(
          java.lang.Iterable<java.lang.String> values) {
        ensureNickNamesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, nickNames_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string nick_names = 4;</code>
       */
      public Builder clearNickNames() {
        nickNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string nick_names = 4;</code>
       */
      public Builder addNickNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureNickNamesIsMutable();
        nickNames_.add(value);
        onChanged();
        return this;
      }

      private int humanType_ = 0;
      /**
       * <code>.resources.Human.HumanType human_type = 5;</code>
       */
      public int getHumanTypeValue() {
        return humanType_;
      }
      /**
       * <code>.resources.Human.HumanType human_type = 5;</code>
       */
      public Builder setHumanTypeValue(int value) {
        humanType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.resources.Human.HumanType human_type = 5;</code>
       */
      public resources.HumanProto.Human.HumanType getHumanType() {
        resources.HumanProto.Human.HumanType result = resources.HumanProto.Human.HumanType.valueOf(humanType_);
        return result == null ? resources.HumanProto.Human.HumanType.UNRECOGNIZED : result;
      }
      /**
       * <code>.resources.Human.HumanType human_type = 5;</code>
       */
      public Builder setHumanType(resources.HumanProto.Human.HumanType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        humanType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.resources.Human.HumanType human_type = 5;</code>
       */
      public Builder clearHumanType() {
        
        humanType_ = 0;
        onChanged();
        return this;
      }

      private resources.HumanProto.Human.Address address_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          resources.HumanProto.Human.Address, resources.HumanProto.Human.Address.Builder, resources.HumanProto.Human.AddressOrBuilder> addressBuilder_;
      /**
       * <code>.resources.Human.Address address = 6;</code>
       */
      public boolean hasAddress() {
        return addressBuilder_ != null || address_ != null;
      }
      /**
       * <code>.resources.Human.Address address = 6;</code>
       */
      public resources.HumanProto.Human.Address getAddress() {
        if (addressBuilder_ == null) {
          return address_ == null ? resources.HumanProto.Human.Address.getDefaultInstance() : address_;
        } else {
          return addressBuilder_.getMessage();
        }
      }
      /**
       * <code>.resources.Human.Address address = 6;</code>
       */
      public Builder setAddress(resources.HumanProto.Human.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          address_ = value;
          onChanged();
        } else {
          addressBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.resources.Human.Address address = 6;</code>
       */
      public Builder setAddress(
          resources.HumanProto.Human.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          address_ = builderForValue.build();
          onChanged();
        } else {
          addressBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.resources.Human.Address address = 6;</code>
       */
      public Builder mergeAddress(resources.HumanProto.Human.Address value) {
        if (addressBuilder_ == null) {
          if (address_ != null) {
            address_ =
              resources.HumanProto.Human.Address.newBuilder(address_).mergeFrom(value).buildPartial();
          } else {
            address_ = value;
          }
          onChanged();
        } else {
          addressBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.resources.Human.Address address = 6;</code>
       */
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = null;
          onChanged();
        } else {
          address_ = null;
          addressBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.resources.Human.Address address = 6;</code>
       */
      public resources.HumanProto.Human.Address.Builder getAddressBuilder() {
        
        onChanged();
        return getAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>.resources.Human.Address address = 6;</code>
       */
      public resources.HumanProto.Human.AddressOrBuilder getAddressOrBuilder() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilder();
        } else {
          return address_ == null ?
              resources.HumanProto.Human.Address.getDefaultInstance() : address_;
        }
      }
      /**
       * <code>.resources.Human.Address address = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          resources.HumanProto.Human.Address, resources.HumanProto.Human.Address.Builder, resources.HumanProto.Human.AddressOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              resources.HumanProto.Human.Address, resources.HumanProto.Human.Address.Builder, resources.HumanProto.Human.AddressOrBuilder>(
                  getAddress(),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:resources.Human)
    }

    // @@protoc_insertion_point(class_scope:resources.Human)
    private static final resources.HumanProto.Human DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new resources.HumanProto.Human();
    }

    public static resources.HumanProto.Human getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Human>
        PARSER = new com.google.protobuf.AbstractParser<Human>() {
      public Human parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Human(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Human> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Human> getParserForType() {
      return PARSER;
    }

    public resources.HumanProto.Human getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_resources_Human_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_resources_Human_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_resources_Human_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_resources_Human_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013human.proto\022\tresources\"\310\002\n\005Human\022\013\n\002id" +
      "\030\221N \001(\t\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\003\022\026\n\016pl" +
      "ace_of_birth\030\003 \001(\t\022\022\n\nnick_names\030\004 \003(\t\022." +
      "\n\nhuman_type\030\005 \001(\0162\032.resources.Human.Hum" +
      "anType\022)\n\007address\030\006 \001(\0132\030.resources.Huma" +
      "n.Address\032Q\n\007Address\022\026\n\016address_line_1\030\001" +
      " \001(\t\022\026\n\016address_line_2\030\002 \001(\t\022\026\n\016address_" +
      "line_3\030\003 \001(\t\"=\n\tHumanType\022\017\n\013SUPER_HUMAN" +
      "\020\000\022\020\n\014NORMAL_HUMAN\020\001\022\r\n\tSUB_HUMAN\020\002B\014B\nH" +
      "umanProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_resources_Human_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_resources_Human_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_resources_Human_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", "PlaceOfBirth", "NickNames", "HumanType", "Address", });
    internal_static_resources_Human_Address_descriptor =
      internal_static_resources_Human_descriptor.getNestedTypes().get(0);
    internal_static_resources_Human_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_resources_Human_Address_descriptor,
        new java.lang.String[] { "AddressLine1", "AddressLine2", "AddressLine3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
